[tool.black]
exclude = '''
/(
    venv
    | __pycache__
)/
'''

[tool.pytest.ini_options]
django_find_project = false
django_settings_module = "backend.settings"

[tool.isort]
line_length = 88
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
