# Generated by Django 5.2.1 on 2025-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_tag_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="description",
            new_name="notes",
        ),
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(
                default="default",
                help_text="URL-friendly identifier for the question",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="e.g., LeetCode, personal interview",
                max_length=4095,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="questionlog",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Solved", "Solved"),
                    ("Partial", "Partial"),
                    ("Failed", "Failed"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
