# Generated by Django 5.2.1 on 2025-07-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="notes",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="questionlog",
            old_name="self_notes",
            new_name="self_content",
        ),
    ]
