# Generated by Django 5.2.1 on 2025-06-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_user_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Easy",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="notes",
            field=models.TextField(
                blank=True,
                default="Default",
                help_text="Detailed description of the question",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="source",
            field=models.CharField(
                blank=True,
                default="Default",
                help_text="e.g., LeetCode, personal interview",
                max_length=4095,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="questionlog",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Solved", "Solved"),
                    ("Partial", "Partial"),
                    ("Failed", "Failed"),
                ],
                default="Default",
                max_length=40,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionlog",
            name="self_notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionlog",
            name="solution_approach",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g., Brute force, Optimized",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Detailed description of the tag"
            ),
            preserve_default=False,
        ),
    ]
