# Generated by Django 5.2.1 on 2025-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_question_difficulty_alter_question_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(
                blank=True,
                editable=False,
                help_text="URL-friendly identifier for the question",
                max_length=255,
                unique=True,
            ),
        ),
    ]
